version: 2.1

### EXECUTORS
executors:
  heycar-citools-helm:
    machine:
      image: ubuntu-2004:202010-01

### COMMANDS

commands:
  circle-default-envs:
    description: "Default Circle Environment variables"
    steps:
      - run: |
          export GIT_BRANCH=${CIRCLE_BRANCH}
          export BUILD_ID=$(echo ${CIRCLE_SHA1} | rev |cut -c1-4 | rev)
          export BUILD_TAG="circleci-${CIRCLE_JOB}-${CIRCLE_BUILD_NUM}"
          export BUILD_DISPLAY_NAME=${CIRCLE_BUILD_NUM}
          export JOB_BASE_NAME=${CIRCLE_JOB}
          export JOB_NAME=${CIRCLE_BUILD_URL}
          echo "export GIT_BRANCH=${GIT_BRANCH}" >> $BASH_ENV
          echo "export BUILD_ID=${BUILD_ID}" >> $BASH_ENV
          echo "export BUILD_TAG=${BUILD_TAG}" >> $BASH_ENV
          echo "export BUILD_DISPLAY_NAME=${BUILD_DISPLAY_NAME}" >> $BASH_ENV
          echo "export JOB_BASE_NAME=${JOB_BASE_NAME}" >> $BASH_ENV
          echo "export JOB_NAME=${JOB_NAME}" >> $BASH_ENV
          source $BASH_ENV

  aws-account-credentials:
    description: "AWS credentials to use"
    parameters:
      aws_access_key_id:
        description: AWS Access Key ID
        type: string
        default: "${AWS_ACCESS_KEY_ID}"
      aws_secret_key:
        description: AWS Secret Key
        type: string
        default: "${AWS_SECRET_ACCESS_KEY}"
    steps:
      - run: |
          export AWS_ACCESS_KEY_ID=<< parameters.aws_access_key_id >>
          export AWS_SECRET_ACCESS_KEY=<< parameters.aws_secret_key >>
          echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $BASH_ENV
          echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $BASH_ENV
          source $BASH_ENV

  docker-build:
    description: "Default Circle Environment variables"
    parameters:
      aws_access_key_id:
        description: AWS Access Key ID
        type: string
        default: "${AWS_ACCESS_KEY_ID}"
      aws_secret_key:
        description: AWS Secret Key
        type: string
        default: "${AWS_SECRET_ACCESS_KEY}"
    steps:
      - run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 728156150350.dkr.ecr.region.amazonaws.com
      
### JOBS

jobs:
  build:
    parameters:
      aws_access_key_id:
         description: aws access key id
         type: string
      aws_secret_key:
         description: aws secret key secret
         type: string
      aws_region:
          description: aws secret key secret
          type: string
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    working_directory: .
    steps:
      - circle-default-envs
      - aws-account-credentials
      - docker-build
      - run:
          name: export env vars
          command: |    
            export AWS_ACCESS_KEY_ID=<< parameters.aws_access_key_id >>
            export AWS_SECRET_ACCESS_KEY=<< parameters.aws_secret_key >>
            export AWS_REGION=<< parameters.aws_region >>
            echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $BASH_ENV
            echo "export AWS_REGION=${AWS_REGION}" >> $BASH_ENV



### WORKFLOWS

workflows:
  version: 2.1

  build:
    jobs:
      - build:
          name: set-environment
          aws_access_key_id: ${AWS_ACCESS_KEY_ID}
          aws_secret_key: ${AWS_SECRET_ACCESS_KEY}
          aws_region: ${AWS_REGION}